// <auto-generated />
namespace ratings.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_002));
        
        string IMigrationMetadata.Id
        {
            get { return "202203091704349_002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
